
CREATE DATABASE T_Rental_DB;
GO

USE master
GO

CREATE TABLE EMPRESA(
 idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(20) NOT NULL
);


CREATE TABLE MARCA (
 idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);


CREATE TABLE CLIENTE(
 idCliente TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeCliente VARCHAR(20) NOT NULL,
 sobrenomeCliente VARCHAR(20) NOT NULL,
 CNH VARCHAR(12) 
 );


 CREATE TABLE MODELO(
 idModelo TINYINT PRIMARY KEY IDENTITY(1,1),
 idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
 nomeModelo VARCHAR(15) NOT NULL
);


 CREATE TABLE VEICULO(
 idVeiculo TINYINT PRIMARY KEY IDENTITY(1,1),
 idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
 idModelo TINYINT FOREIGN KEY REFERENCES MODELO(idModelo),
 placaVeiculo VARCHAR(8) NOT NULL
);

CREATE TABLE ALUGUEL(
 idAluguel TINYINT PRIMARY KEY IDENTITY(1,1),
 idCliente TINYINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
 idVeiculo TINYINT FOREIGN KEY REFERENCES VEICULO (idVeiculo),
 dataInicio DATETIME,
 dataFim DATETIME
);

SELECT idAluguel,  idEmpresa, idCliente, idVeiculo, dataInicio, dataFim FROM ALUGUEL WHERE idAluguel = @idAluguel;